spring.application.name=entrenador
server.port=8081


# Configuración para XAMPP
spring.datasource.url=jdbc:mysql://localhost:3306/db_fitchain_clientes
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true