spring.application.name=entrenador
server.port=8081


spring.datasource.url=
spring.datasource.username=root
spring.datasource.password=


# update: crea las tablas si no existen, las actualiza
# si el modelo cambió. Ideal para desarrollo en clase.
spring.jpa.hibernate.ddl-auto=create-drop


# Muestra en consola el SQL que ejecuta Hibernate.
# Útil para entender qué ocurre internamente.
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect